# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f02933f2737da65364f0d0baaf25ccf9fbf5d57fb3c6620b9c033ca695c53276a254ca10cea601d3917bb595c7835afc15c8f0aaa62bff3218a4b07127fac08e

test:
  secret_key_base: fe63ec646c440015253b5c2e01ea5330782f8ea78bbefc12d7038e2e791ca2e68085cdbea05e9c41a0381752fd2f21325513343083a60117b5d0aa55c1c649f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
